### ISSUE TITLE
forwarding to private method

### ISSUE THREAD

**Issue by aleksey-alt** [tpitale/staccato#89]
From my server logs:

```
347 <190>1 2019-10-15T19:47:49.785532+00:00 app worker.1 - - /app/vendor/bundle/ruby/2.6.0/gems/staccato-0.5.1/lib/staccato/measurement/product.rb:14: warning: Staccato::Measurement::Product#index at /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method Staccato::OptionSet#index
```

**Comment by tpitale** [comment]
Interesting, I haven't seen that warning before.

**Comment by tpitale** [comment]
Hrm. I can't seem to reproduce (on a console) with ruby 2.6.3 and staccato 0.5.3.

`index` does not appear to be a method on `OpenStruct` (`OptionSet` is an `OpenStruct`) https://github.com/ruby/ruby/blob/master/lib/ostruct.rb

And any method created by `OpenStruct` from the initial argument hash passed in should be public. I can't find any indication otherwise either in ruby or in staccato.

It could be a bug in 2.6.0 (or even 2.4) that was fixed later, by 2.6.3.

I found a reference to a ticket of a similar issue that was resolved in this commit: https://github.com/thoughtbot/shoulda-matchers/pull/1038/files. This seems like it was a workaround for something started here: https://github.com/thoughtbot/shoulda-matchers/issues/1006

**Comment by tpitale** [comment]
@aleksey-alt If you could, try 2.6.3? I'm not sure what else I can do. If I have time, I'll try to downgrade to 2.6.0 and see if I can reproduce.

**Comment by aleksey-alt** [comment]
@tpitale We already use ruby 2.6.3:

```
... at /app/vendor/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method Staccato::OptionSet#index
```

And I created small script for reproducing the issue:

```
require 'forwardable'
require "ostruct"

class Abc
  extend Forwardable

  attr_accessor :os
  def_delegators :@os, :index

  def initialize
    @os = ::OpenStruct.new
  end
end

Abc.new.index
```

```
$ ruby abc.rb
abc.rb:15: warning: Abc#index at /home/tux/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method OpenStruct#index
```

**Comment by tpitale** [comment]
Oh, I see. You’re not passing in an index value. So openstructs error is confusing. It’s basically an undefined method.

I’ll try to make the error more clear.

**Comment by tpitale** [comment]
Just as an example:

```rb
require 'forwardable'
require "ostruct"

class Abc
  extend Forwardable

  attr_accessor :os
  def_delegators :@os, :index

  def initialize
    @os = ::OpenStruct.new(index: 1)
  end
end

Abc.new.index #=> 1
```

**Comment by tpitale** [comment]
https://github.com/tpitale/staccato/commit/9eab8905c56bb89274a71fe3fa31246f39cc56ef Raises if index is nil. This should be more clear.
